name: Django-DevPro Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      PIPENV_VENV_IN_PROJECT: 1
      PIPENV_NO_INHERIT: 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv sync --dev
      - name: Lint with flake8
        run: |
          pipenv run flake8 .